LANES = ["A","B","C"]
MINIMUM_START_VELOCITY = 1
MAXMUM_START_VELOCITY = 8
MINIMUM_START_ACCELERATION = -1 
MAXIMUM_START_ACCELERATION = 1
MIN_LENGTH = 2 
MAX_LENGTH = 5 
MIN_WIDTH = 1 
MAX_WIDTH = 2

MAX_CARS = 4